name: streaming_sound
description: "A new Flutter FFI plugin project."
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  native_assets_cli: ^0.9.0
  native_toolchain_c: ^0.6.0

dev_dependencies:
  ffigen: ^16.0.0
  flutter_lints: ^5.0.0
  logging: ^1.3.0
  test: ^1.25.8
# flutter:
#   plugin:
#     platforms:
#       android:
#         ffiPlugin: true
#       ios:
#         ffiPlugin: true
#       linux:
#         ffiPlugin: true
#       macos:
#         ffiPlugin: true
#       windows:
#         ffiPlugin: true
